#include "ip.h"
#include "icmp.h"
#include "packet.h"
#include "arpcache.h"
#include "rtable.h"
#include "arp.h"

// #include "log.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// initialize ip header 
void ip_init_hdr(struct iphdr *ip, u32 saddr, u32 daddr, u16 len, u8 proto)
{
	ip->version = 4;
	ip->ihl = 5;
	ip->tos = 0;
	ip->tot_len = htons(len);
	ip->id = rand();
	ip->frag_off = htons(IP_DF);
	ip->ttl = DEFAULT_TTL;
	ip->protocol = proto;
	ip->saddr = htonl(saddr);
	ip->daddr = htonl(daddr);
	ip->checksum = ip_checksum(ip);
}

// lookup in the routing table, to find the entry with the same and longest prefix.
// the input address is in host byte order
rt_entry_t *longest_prefix_match(u32 dst)
{
	/*fprintf(stderr, "TODO: longest prefix match for the packet.\n");*/
	rt_entry_t *entry = NULL;
	rt_entry_t *temp = NULL;
	u32 max_prefix = 0;

	list_for_each_entry(entry, &rtable, list) {
		if((entry->dest & entry->mask) == (dst & entry->mask) && (entry->mask > max_prefix)) 
		{
			temp = entry;
			max_prefix = entry->mask;
		}
	}
	return temp;
}

// send IP packet
//
// Different from forwarding packet, ip_send_packet sends packet generated by
// router itself. This function is used to send ICMP packets.
void ip_send_packet(char *packet, int len)
{
	// fprintf(stderr, "TODO: send ip packet.\n");
	struct iphdr *iph = packet_to_ip_hdr(packet);
	u32 dst = ntohl(iph->daddr);
	rt_entry_t *entry = longest_prefix_match(dst);
	if(!entry)
		return;

	u32 next_hop = entry->gw ? entry->gw : dst;
	
	struct ether_header *eh = (struct ether_header *)packet;
	eh->ether_type = ntohs(ETH_P_IP);
	memcpy(eh->ether_shost, entry->iface->mac, ETH_ALEN);
	// 使用 iface_send_packet_by_arp()发送；
	iface_send_packet_by_arp(entry->iface, next_hop, packet, len);
}
